name: Arido
description: A new Flutter project for Arido company.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  webview_flutter: ^2.0.13
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.1.0
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.2
  build_runner: ^2.4.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21  # حداقل نسخه SDK برای اندروید (اختیاری)
  adaptive_icon_background: "#FFFFFF"  # رنگ پس‌زمینه برای آیکون اندروید
  adaptive_icon_foreground: "assets/logo.png"  # تصویر آیکون برای نسخه‌های جدید اندروید

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/favicon.ico
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
